# Generated by Django 4.2.5 on 2023-10-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("stadium", models.CharField(max_length=500)),
                ("poster", models.ImageField(null=True, upload_to="images/%y/%m/%d")),
                ("date", models.DateTimeField()),
                ("vName", models.CharField(max_length=500)),
                ("vLogo", models.ImageField(null=True, upload_to="images/%y/%m/%d")),
                ("vResult", models.CharField(max_length=1)),
                ("sResult", models.CharField(max_length=1)),
                ("vGoals", models.TextField()),
                ("sGoals", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=2000)),
                ("video", models.FileField(null=True, upload_to="videos/%y/%m/%d")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=2000)),
                ("text", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/%y/%m/%d"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("number", models.CharField(max_length=2)),
                ("nationality", models.CharField(max_length=100)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("GK", "حارس مرمى"),
                            ("DF", "مدافع"),
                            ("MD", "متوسط ميدان"),
                            ("ST", "مهاجم"),
                            ("M", "المدرب"),
                            ("S", "الطاقم الفني"),
                        ],
                        max_length=100,
                    ),
                ),
                ("join", models.DateField()),
                ("text", models.TextField()),
            ],
        ),
    ]
