# Generated by Django 4.2.5 on 2023-10-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="competition",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
