# Generated by Django 4.2.5 on 2023-10-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_match_competition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="competition",
            field=models.ImageField(null=True, upload_to="images/%y/%m/%d"),
        ),
    ]
