# Generated by Django 4.2.5 on 2023-10-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_media_category_alter_news_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/%y/%m/%d"),
        ),
    ]
