# Generated by Django 4.2.5 on 2023-10-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_player_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="image",
            field=models.ImageField(
                blank=True,
                default="images/Pdefault.png' %",
                null=True,
                upload_to="images/%y/%m/%d",
            ),
        ),
    ]
