# Generated by Django 4.2.5 on 2023-10-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_player_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/%y/%m/%d"),
        ),
    ]
