# Generated by Django 4.2.5 on 2023-10-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_player_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="category",
            field=models.CharField(
                choices=[("الفريق الأول", "first team"), ("الطائرة", "volleyball")],
                max_length=100,
                null=True,
            ),
        ),
    ]
