# Generated by Django 4.2.5 on 2023-11-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_media_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="category",
            field=models.CharField(
                choices=[
                    ("الملخصات", "highlights"),
                    ("الأرشيف", "archive"),
                    ("لقاءات إعلامية", "meetings"),
                    ("الطائرة", "volleyball"),
                ],
                max_length=100,
            ),
        ),
    ]
